application: home-screen-1149
version: 2
runtime: python27
instance_class: B1
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: homescreen/static/favicon.ico
  upload: homescreen/static/favicon\.ico
- url: /static
  static_dir: homescreen/static
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: "2.3.5"
- name: webob
  version: "1.2.3"

